#!/usr/bin/env bash
# Builds the site into public/. Replaces UVKBuildTool (and install.sh, ci-clean.sh and the three
# sed passes the deploy workflow used to run).
#
#   ./build.sh          production build
#   ./build.sh --serve  build and serve on http://localhost:8080
set -euo pipefail
cd "$(dirname "$0")"

SERVE=false
[ "${1:-}" = "--serve" ] && { SERVE=true; shift; }

# --- <lastmod> dates, from git -------------------------------------------------------------------
# Replaces .github/update-sitemap-lastmod.py. A page's date moves only when something that actually
# renders it changed: its own layout, the shared chrome, or the translations.
CHROME=(layouts/baseof.html layouts/_partials data/translations)
{
    echo "# Generated by build.sh from git history; do not edit."
    for slug in index deck account marketplace privacy; do
        date=$(git log -1 --format=%cs -- "layouts/${slug}.html" "${CHROME[@]}" 2>/dev/null || true)
        echo "${slug}: \"${date:-$(date +%F)}\""
    done
} > data/lastmod.yaml

# --- build ---------------------------------------------------------------------------------------
rm -rf public
hugo --gc --minify "$@"

# --- locale directories --------------------------------------------------------------------------
# Hugo lowercases the language key when deriving the output directory. The cased names are part of
# the site's public URLs (SUPPORTED_LOCALES in language-selector.js, the `language` localStorage
# value, existing bookmarks), and every link in the templates is built from params.dir, so the
# directories are simply renamed back here.
for dir in en_US bg_BG ro_RO; do
    lower=$(echo "$dir" | tr '[:upper:]' '[:lower:]')
    [ -d "public/$lower" ] && mv "public/$lower" "public/$dir"
done

# --- root mirror ---------------------------------------------------------------------------------
# The root serves a copy of the default locale, exactly as the old build did: it is the sitemap's
# x-default and the landing page for crawlers and for visitors without JavaScript (setLanguage() in
# language-selector.js redirects everyone else into their locale directory). Hugo leaves a meta
# refresh stub at the root; replace it.
rm -f public/index.html
cp -r public/en_US/. public/
# Guard against a template directive reaching the output: a file that carries {{ ... }} but is not
# run through resources.ExecuteAsTemplate fails silently, shipping the literal directive as content.
if leaked=$(grep -rlE '\{\{[ -]*(site\.Params|partial|i18n|hugo\.)' public/ 2>/dev/null); then
    echo "ERROR: unsubstituted template directives in the build output:" >&2
    echo "$leaked" >&2
    exit 1
fi

echo "Built $(find public -type f | wc -l) files into public/"

# --- serve ---------------------------------------------------------------------------------------
# `hugo server` is not used: it renders from memory under Hugo's lowercased locale directories, so
# the rename above (and therefore every link in the pages) would not apply. Serving the finished
# public/ tree is also what the old run.sh did.
if [ "$SERVE" = true ]; then
    echo "Serving http://localhost:8080/ (Ctrl-C to stop)"
    exec python3 -m http.server 8080 --directory public
fi
